name: Build

on:
  push:
  pull_request:

jobs:
  build:
    name: Build
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly

      - name: Build
        run: cargo build --release --features=${{ matrix.features }}

      - name: Create output dir
        run: mkdir output

      - name: Copy artifact binaries to output directory
        run: |
          xcopy README.md output\
          xcopy include\*.h output\
          xcopy target\release\*.lib output\

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Binaries
          path: |
            output\**

  bundle:
    name: Bundle
    runs-on: windows-latest
    needs: [build]
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: Binaries
          path: release\

      - name: Bundle binaries
        run: 7z a -tzip Library.zip .\release\**

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: Library.zip